// types/viewer.ts - Viewer 核心类型定义

export const MAX_LINES = 500;
export const DEFAULT_PORT = 38888;
export const TOOL_CALL_MAX_LINES = 5;
export const HISTORY_SAVE_DEBOUNCE_MS = 800;

export type LayoutMode = "list" | "grid";
export type RunStatus = "running" | "completed" | "error";
export type ConnectionState = "connecting" | "connected" | "error";
export type Language = "zh" | "en";
export type Theme = "dark" | "light";

export type StreamLine = {
    type: "user" | "agent" | "tool_start" | "tool_end" | "output" | "thinking" | "error" | "info" | "file_op";
    content: string;
    status?: "running" | "success" | "failed";
    duration?: string;
};

export type CodeChanges = {
    filesChanged: number;
    linesAdded: number;
    linesRemoved: number;
};

export type RunState = {
    id: string;
    runIds: string[];
    projectRoot?: string;
    sessionId?: string | null;
    status: RunStatus;
    startedAt?: string;
    completedAt?: string;
    success?: boolean;
    exitCode?: number;
    errorType?: string;
    duration?: number;
    turnCount: number;
    thinkingStartTime?: number;
    lines: StreamLine[];
    codeChanges: CodeChanges;
};

export type ViewerSettings = { port: number };

export const translations = {
    zh: {
        title: "cc-spec tools",
        subtitle: "项目管理与执行监控",
        clearRuns: "清空",
        runs: "执行任务",
        waitingEvents: "等待 Codex 执行...",
        projects: "项目",
        projectHint: "导入本地项目，作为会话、索引与技能的管理入口",
        currentProject: "当前项目",
        noProjectSelected: "尚未选择项目",
        projectPathPlaceholder: "输入项目路径（例如 C:\\develop\\cc-spec）",
        projectPathRequired: "请先输入项目路径",
        importProject: "导入项目",
        refresh: "刷新",
        projectList: "项目列表",
        setCurrent: "设为当前",
        enterProject: "进入",
        removeProject: "移除",
        noProjects: "暂无项目记录",
        openClaudeTerminal: "打开 Claude 终端",
        loading: "加载中",
        projectNotFound: "项目不存在或已被移除",
        confirmRemoveProject: "确认从列表移除此项目？",
        cancel: "取消",
        removeProjectDialogTitle: "移除项目",
        removeProjectDialogSubtitle: "可选备份需求文档，其他 cc-spec 产物将彻底清理",
        removeProjectDialogDesc: "选择“卸载并清理后移除”将删除项目内 .cc-spec/、.cc-specignore、.claude/commands/cc-spec*、.claude/skills/cc-spec-standards，并清理本机工具历史记录与项目状态。",
        backupRequirementsLabel: "删除前备份需求文档",
        backupRequirementsHint: "仅备份 proposal.md / detail.md / review.md / mini-proposal.md",
        backupSaveDialogTitle: "选择需求备份文件位置",
        backupPathInProjectError: "备份文件不能保存在项目目录内（清理会删除该路径），请重新选择。",
        removeProjectOnly: "仅从列表移除",
        removeProjectCleanupAndRemove: "卸载并清理后移除",
        removeProjectWorking: "处理中...",
        selectProjectHint: "先导入并选择项目，运行记录将按项目归档显示。",
        projectEmpty: "暂无运行记录",
        projectEmptyHint: "当前项目还没有 Codex 运行记录。",
        navProjects: "项目中心",
        navRuns: "运行列表",
        navCommandsGuide: "Commands 指南",
        backToProjects: "返回项目中心",
        projectTabOverview: "概览",
        projectTabSkills: "Skills",
        projectTabArtifacts: "产物",
        projectTabRuns: "运行",
        yes: "是",
        no: "否",
        openInVSCode: "在 VS Code 打开",
        projectIndexTitle: "索引",
        projectIndexInitialized: "是否初始化",
        projectIndexLevels: "Levels",
        projectIndexFiles: "文件数",
        projectIndexUpdatedAt: "更新时间",
        projectChangesTitle: "变更",
        projectChangesHint: "从 .cc-spec/changes 读取 status.yaml 汇总",
        projectChangesCount: "数量",
        projectChangesEmpty: "暂无变更记录",
        artifactsTitle: "cc-spec 产物",
        artifactsHint: "浏览项目内 cc-spec 生成的文件，默认在 VS Code 中编辑",
        artifactsBrowser: "浏览",
        artifactFolder: "文件夹",
        notGenerated: "未生成",
        notGeneratedHint: "该项尚未生成或已被清理",
        up: "上一级",
        emptyFolder: "空文件夹",
        preview: "预览",
        reveal: "在资源管理器中显示",
        copyPath: "复制路径",
        jumpToLine: "跳转到行",
        openAtLine: "打开到行",
        previewFromLine: "从该行预览",
        selectArtifactHint: "请选择一个产物目录/文件",
        selectFileHint: "选择一个文件以预览（目录仅用于浏览）",
        lines: "Lines",
        truncated: "已截断",
        loadMore: "继续",
        noPreview: "暂无可预览内容",
        commandsTitle: "Commands 管理",
        commandsHint: "将 cc-spec commands 安装到当前项目的 .claude/commands",
        commandsVersion: "内置版本",
        commandsUpdateNeeded: "需要更新",
        commandsUpToDate: "已是最新",
        commandsInstall: "安装/更新",
        commandsUninstall: "卸载",
        commandsRefresh: "刷新状态",
        commandsNoProject: "请选择项目后管理 Commands",
        commandsEmpty: "暂无 Commands 状态，请刷新或安装",
        commandsInstalled: "已安装",
        commandsMissing: "未安装",
        active: "活跃",
        completed: "已完成",
        statusLive: "Running",
        statusDone: "Done",
        statusFailed: "Failed",
        statusIdle: "Idle",
        started: "开始",
        finished: "结束",
        duration: "耗时",
        exitCode: "退出码",
        errorType: "错误",
        noOutput: "暂无输出",
        connecting: "连接中...",
        connected: "已连接",
        connectionError: "断开重连中...",
        port: "端口",
        langMode: "English",
        copy: "复制",
        copied: "已复制",
        darkMode: "深色",
        lightMode: "浅色",
        stop: "停止",
        stopping: "停止中...",
        // IndexPrompt
        indexPromptTitle: "初始化项目索引",
        indexPromptSubtitle: "创建多级索引以提升 AI 辅助效果",
        indexPromptDesc: "索引可以帮助 Claude Code 更好地理解您的项目结构。请选择要生成的索引级别：",
        indexL1Name: "L1 - 摘要",
        indexL1Desc: "项目结构概览",
        indexL2Name: "L2 - 符号",
        indexL2Desc: "函数、类、导出等",
        indexL3Name: "L3 - 详情",
        indexL3Desc: "完整代码分析（较慢）",
        indexDontAskAgain: "不再提示",
        indexSkip: "跳过",
        indexInitialize: "初始化",
        indexInitializing: "初始化中...",
    },
    en: {
        title: "cc-spec tools",
        subtitle: "Project hub and execution monitor",
        clearRuns: "Clear",
        runs: "Runs",
        waitingEvents: "Waiting for Codex...",
        projects: "Projects",
        projectHint: "Import a local project to manage sessions, indexes, and skills.",
        currentProject: "Current Project",
        noProjectSelected: "No project selected",
        projectPathPlaceholder: "Enter project path (e.g. C:\\develop\\cc-spec)",
        projectPathRequired: "Please enter a project path",
        importProject: "Import Project",
        refresh: "Refresh",
        projectList: "Project List",
        setCurrent: "Set Current",
        removeProject: "Remove",
        noProjects: "No projects yet",
        openClaudeTerminal: "Open Claude Terminal",
        loading: "Loading",
        projectNotFound: "Project not found or removed",
        confirmRemoveProject: "Remove this project from the list?",
        cancel: "Cancel",
        removeProjectDialogTitle: "Remove project",
        removeProjectDialogSubtitle: "Optionally back up requirements; everything else will be cleaned",
        removeProjectDialogDesc: "Choosing “Uninstall & clean, then remove” deletes .cc-spec/, .cc-specignore, .claude/commands/cc-spec*, .claude/skills/cc-spec-standards, and clears local tool history and project state.",
        backupRequirementsLabel: "Back up requirements before deleting",
        backupRequirementsHint: "Exports proposal.md / detail.md / review.md / mini-proposal.md only",
        backupSaveDialogTitle: "Choose requirements backup location",
        backupPathInProjectError: "Backup file cannot be saved inside the project folder (cleanup will delete it). Choose another location.",
        removeProjectOnly: "Remove from list only",
        removeProjectCleanupAndRemove: "Uninstall & clean, then remove",
        removeProjectWorking: "Working...",
        selectProjectHint: "Import and select a project to view runs grouped by project.",
        projectEmpty: "No runs yet",
        projectEmptyHint: "There are no Codex runs for the current project.",
        navProjects: "Projects",
        navRuns: "Runs",
        navCommandsGuide: "Commands Guide",
        enterProject: "Enter",
        backToProjects: "Back to Projects",
        projectTabOverview: "Overview",
        projectTabSkills: "Skills",
        projectTabArtifacts: "Artifacts",
        projectTabRuns: "Runs",
        yes: "Yes",
        no: "No",
        openInVSCode: "Open in VS Code",
        projectIndexTitle: "Index",
        projectIndexInitialized: "Initialized",
        projectIndexLevels: "Levels",
        projectIndexFiles: "Files",
        projectIndexUpdatedAt: "Updated",
        projectChangesTitle: "Changes",
        projectChangesHint: "Reads status.yaml from .cc-spec/changes",
        projectChangesCount: "Count",
        projectChangesEmpty: "No changes yet",
        artifactsTitle: "cc-spec artifacts",
        artifactsHint: "Browse cc-spec outputs (edit in VS Code by default)",
        artifactsBrowser: "Browser",
        artifactFolder: "Folder",
        notGenerated: "Missing",
        notGeneratedHint: "This item is not generated or has been cleaned",
        up: "Up",
        emptyFolder: "Empty folder",
        preview: "Preview",
        reveal: "Reveal in file manager",
        copyPath: "Copy path",
        jumpToLine: "Jump to line",
        openAtLine: "Open at line",
        previewFromLine: "Preview from line",
        selectArtifactHint: "Select an artifact root/file",
        selectFileHint: "Select a file to preview (directories are for browsing)",
        lines: "Lines",
        truncated: "truncated",
        loadMore: "More",
        noPreview: "Nothing to preview",
        commandsTitle: "Commands Manager",
        commandsHint: "Install cc-spec commands into .claude/commands for this project.",
        commandsVersion: "Bundled Version",
        commandsUpdateNeeded: "Update Needed",
        commandsUpToDate: "Up to Date",
        commandsInstall: "Install/Update",
        commandsUninstall: "Uninstall",
        commandsRefresh: "Refresh",
        commandsNoProject: "Select a project to manage commands.",
        commandsEmpty: "No commands status yet. Refresh or install.",
        commandsInstalled: "Installed",
        commandsMissing: "Missing",
        active: "Active",
        completed: "Done",
        statusLive: "Running",
        statusDone: "Done",
        statusFailed: "Failed",
        statusIdle: "Idle",
        started: "Started",
        finished: "Finished",
        duration: "Duration",
        exitCode: "Exit",
        errorType: "Error",
        noOutput: "No output",
        connecting: "Connecting...",
        connected: "Connected",
        connectionError: "Reconnecting...",
        port: "Port",
        langMode: "中文",
        copy: "Copy",
        copied: "Copied",
        darkMode: "Dark",
        lightMode: "Light",
        stop: "Stop",
        stopping: "Stopping...",
        // IndexPrompt
        indexPromptTitle: "Initialize Project Index",
        indexPromptSubtitle: "Create a multi-level index for better AI assistance",
        indexPromptDesc: "An index helps Claude Code understand your project structure. Select the levels you want to generate:",
        indexL1Name: "L1 - Summary",
        indexL1Desc: "Project structure overview",
        indexL2Name: "L2 - Symbols",
        indexL2Desc: "Functions, classes, exports",
        indexL3Name: "L3 - Details",
        indexL3Desc: "Full code analysis (slower)",
        indexDontAskAgain: "Don't ask again",
        indexSkip: "Skip",
        indexInitialize: "Initialize",
        indexInitializing: "Initializing...",
    },
};

export const BG_IMAGES = [
    '122.png',
    '6fc129ee-5c9e-4f10-804b-0f73f198347b.png',
    'A8430D51D6F00D3A6CE72F04DC47C8FE.gif',
    'miao.gif',
    'ScreenShot_2025-12-17_175919_945.png',
    'wu.jpg'
];
