// types/viewer.ts - Viewer 核心类型定义

export const MAX_LINES = 500;
export const DEFAULT_PORT = 38888;
export const TOOL_CALL_MAX_LINES = 5;
export const HISTORY_SAVE_DEBOUNCE_MS = 800;

export type LayoutMode = "list" | "grid";
export type RunStatus = "running" | "completed" | "error";
export type ConnectionState = "connecting" | "connected" | "error";
export type Language = "zh" | "en";
export type Theme = "dark" | "light";

export type StreamLine = {
    type: "user" | "agent" | "tool_start" | "tool_end" | "output" | "thinking" | "error" | "info" | "file_op";
    content: string;
    status?: "running" | "success" | "failed";
    duration?: string;
};

export type CodeChanges = {
    filesChanged: number;
    linesAdded: number;
    linesRemoved: number;
};

export type RunState = {
    id: string;
    runIds: string[];
    projectRoot?: string;
    sessionId?: string | null;
    status: RunStatus;
    startedAt?: string;
    completedAt?: string;
    success?: boolean;
    exitCode?: number;
    errorType?: string;
    duration?: number;
    turnCount: number;
    thinkingStartTime?: number;
    lines: StreamLine[];
    codeChanges: CodeChanges;
};

export type ViewerSettings = { port: number };

export const translations = {
    zh: {
        title: "cc-spec tools",
        subtitle: "项目管理与执行监控",
        clearRuns: "清空",
        runs: "执行任务",
        waitingEvents: "等待 Codex 执行...",
        projects: "项目",
        projectHint: "导入本地项目，作为会话、索引与技能的管理入口",
        currentProject: "当前项目",
        noProjectSelected: "尚未选择项目",
        projectPathPlaceholder: "输入项目路径（例如 C:\\develop\\cc-spec）",
        projectPathRequired: "请先输入项目路径",
        importProject: "导入项目",
        refresh: "刷新",
        projectList: "项目列表",
        setCurrent: "设为当前",
        enterProject: "进入",
        removeProject: "移除",
        noProjects: "暂无项目记录",
        openClaudeTerminal: "打开 Claude 终端",
        loading: "加载中",
        projectNotFound: "项目不存在或已被移除",
        confirmRemoveProject: "确认从列表移除此项目？",
        cancel: "取消",
        removeProjectDialogTitle: "移除项目",
        removeProjectDialogSubtitle: "可选备份需求文档，其他 cc-spec 产物将彻底清理",
        removeProjectDialogDesc: "选择“卸载并清理后移除”将删除项目内 .cc-spec/、.cc-specignore、.claude/commands/cc-spec*、.claude/skills/cc-spec-standards，并清理本机工具历史记录与项目状态。",
        backupRequirementsLabel: "删除前备份需求文档",
        backupRequirementsHint: "仅备份 proposal.md / detail.md / review.md / mini-proposal.md",
        backupSaveDialogTitle: "选择需求备份文件位置",
        backupPathInProjectError: "备份文件不能保存在项目目录内（清理会删除该路径），请重新选择。",
        removeProjectOnly: "仅从列表移除",
        removeProjectCleanupAndRemove: "卸载并清理后移除",
        removeProjectWorking: "处理中...",
        selectProjectHint: "先导入并选择项目，运行记录将按项目归档显示。",
        projectEmpty: "暂无运行记录",
        projectEmptyHint: "当前项目还没有 Codex 运行记录。",
        navProjects: "项目中心",
        navRuns: "运行列表",
        navCommandsGuide: "Commands 指南",
        backToProjects: "返回项目中心",
        projectTabOverview: "概览",
        projectTabSkills: "Skills",
        projectTabArtifacts: "产物",
        projectTabRuns: "运行",
        projectTabCodex: "Codex",
        yes: "是",
        no: "否",
        openInVSCode: "在 VS Code 打开",
        empty: "暂无",
        projectIndexTitle: "索引",
        projectIndexInitialized: "是否初始化",
        projectIndexLevels: "Levels",
        projectIndexFiles: "文件数",
        projectIndexUpdatedAt: "更新时间",
        reinitIndex: "重新初始化",
        projectChangesTitle: "变更",
        projectChangesHint: "从 .cc-spec/changes 读取 status.yaml 汇总",
        projectChangesCount: "数量",
        projectChangesEmpty: "暂无变更记录",
        artifactsTitle: "cc-spec 产物",
        artifactsHint: "浏览项目内 cc-spec 生成的文件，默认在 VS Code 中编辑",
        artifactsBrowser: "浏览",
        artifactFolder: "文件夹",
        notGenerated: "未生成",
        notGeneratedHint: "该项尚未生成或已被清理",
        up: "上一级",
        emptyFolder: "空文件夹",
        preview: "预览",
        reveal: "在资源管理器中显示",
        copyPath: "复制路径",
        jumpToLine: "跳转到行",
        openAtLine: "打开到行",
        previewFromLine: "从该行预览",
        selectArtifactHint: "请选择一个产物目录/文件",
        selectFileHint: "选择一个文件以预览（目录仅用于浏览）",
        lines: "Lines",
        truncated: "已截断",
        loadMore: "继续",
        noPreview: "暂无可预览内容",
        commandsTitle: "Commands 管理",
        commandsHint: "将 cc-spec commands 安装到当前项目的 .claude/commands",
        commandsVersion: "内置版本",
        commandsUpdateNeeded: "需要更新",
        commandsUpToDate: "已是最新",
        commandsInstall: "安装/更新",
        commandsUninstall: "卸载",
        commandsRefresh: "刷新状态",
        commandsNoProject: "请选择项目后管理 Commands",
        commandsEmpty: "暂无 Commands 状态，请刷新或安装",
        commandsInstalled: "已安装",
        commandsMissing: "未安装",
        active: "活跃",
        completed: "已完成",
        statusLive: "Running",
        statusDone: "Done",
        statusFailed: "Failed",
        statusIdle: "Idle",
        started: "开始",
        finished: "结束",
        duration: "耗时",
        exitCode: "退出码",
        errorType: "错误",
        noOutput: "暂无输出",
        connecting: "连接中...",
        connected: "已连接",
        connectionError: "断开重连中...",
        port: "端口",
        langMode: "English",
        copy: "复制",
        copied: "已复制",
        darkMode: "深色",
        lightMode: "浅色",
        stop: "停止",
        pause: "暂停",
        send: "发送",
        stopping: "停止中...",
        projectCodexHint: "用户在原生终端操作；tool 负责会话/重试/暂停/结果通知",
        projectCodexNewSession: "新建会话",
        projectCodexSessions: "会话列表",
        projectCodexSelected: "当前会话",
        projectCodexSend: "发送一条提示（注入终端）",
        projectCodexPromptPlaceholder: "例如：总结这个项目的结构…",
        projectCodexSendHint: "Claude Code 可订阅 codex.managed.turn_complete 拿到最终结果",
        projectCodexLastResult: "最后一次结果",
        // IndexPrompt
        indexPromptTitle: "初始化项目（必需）",
        indexPromptSubtitle: "生成 Commands/Standards 并初始化索引",
        indexPromptDesc: "将执行：1) Bootstrap（生成 .claude/commands 与 standards）；2) Index（生成 PROJECT_INDEX/FOLDER_INDEX）。请选择索引级别（推荐 L1 + L2）：",
        indexL1Name: "L1 - 摘要",
        indexL1Desc: "项目结构概览",
        indexL2Name: "L2 - 符号",
        indexL2Desc: "函数、类、导出等",
        indexL3Name: "L3 - 详情",
        indexL3Desc: "完整代码分析（较慢）",
        indexDontAskAgain: "不再提示",
        indexSkip: "跳过",
        indexInitialize: "初始化",
        indexInitializing: "初始化中...",
        // TriggerEditor
        keywordExists: "关键词已存在",
        invalidRegex: "无效的正则表达式",
        patternExists: "模式已存在",
        enterKeyword: "输入关键词，按回车添加",
        enterRegex: "输入正则表达式，按回车添加",
        testText: "输入测试文本，实时查看匹配结果...",
        matchTest: "测试中...",
        // BodyEditor
        edit: "编辑",
        saving: "保存中...",
        save: "保存",
        enterMarkdown: "在这里编写 Markdown 内容...",
        // SkillsPage
        workflow: "工作流",
        domain: "领域",
        execution: "执行",
        enabled: "启用",
        disabled: "禁用",
        details: "详情",
        collapse: "收起",
        scanDirectory: "扫描目录",
        // ProjectSkillsPanel
        skillsUpdated: "项目 Skills 状态已更新",
        scanning: "扫描中...",
        scanProjectDir: "扫描项目目录",
        removeFromProject: "从项目移除",
        selectProjectFirst: "请先选择一个项目",
        clickToScan: "点击「扫描项目目录」来检测项目 Skills",
        // ProjectCodexPanel
        confirmStopAndDelete: "确认：会话仍在运行，是否停止并删除记录？",
        confirmDeleteSession: "确认：是否删除此会话记录？",
        deleteSession: "删除会话（运行中会先停止）",
        sessionStatus: "会话状态",
        // TitleBar
        minimize: "最小化",
        maximizeRestore: "最大化/还原",
        close: "关闭",
        // Settings 页面
        settingsTitle: "设置",
        settingsDesc: "配置应用参数、并发限制及模型选项",
        goBack: "返回",
        savingSettings: "保存中...",
        saveSettings: "保存设置",
        settingsSaved: "设置已保存！",
        concurrencyStatus: "并发状态",
        queued: "排队",
        total: "总计",
        concurrencyLimitReached: "达到并发上限，新任务将排队等待",
        claudeConfig: "Claude 配置",
        execPath: "执行路径",
        autoDetect: "自动检测",
        customPath: "自定义路径",
        enterClaudePath: "输入 claude 可执行文件路径",
        maxConcurrent: "最大并发数",
        suggestedValue: "建议值: 1-2",
        uiDisplay: "界面显示",
        theme: "主题",
        followSystem: "跟随系统",
        darkTheme: "深色模式",
        lightTheme: "浅色模式",
        languageLabel: "语言",
        chineseSimplified: "简体中文",
        englishLang: "English",
        codexConfig: "Codex 配置",
        indexSettings: "索引设置",
        enableMultiLevelIndex: "启用多级索引",
        autoUpdateIndex: "自动更新索引",
        translationModel: "翻译模型",
        loaded: "已加载",
        downloaded: "已下载",
        notDownloaded: "未下载",
        currentModelLabel: "当前模型",
        noneModel: "无",
        fileSize: "文件大小",
        cacheEntriesLabel: "缓存条目",
        translationModelDesc: "支持从 HuggingFace 下载多种翻译模型，包括 T5、Opus MT 等。",
        openModelManager: "打开模型管理",
        refreshStatus: "刷新状态",
        clearCache: "清空缓存",
        // ModelManager 页面
        modelManager: "模型管理",
        modelManagerDesc: "下载、加载和管理翻译模型，监控资源占用",
        refreshing: "刷新中...",
        backToSettings: "返回设置",
        loadFailed: "加载失败",
        downloadFailed: "下载失败",
        unloadFailed: "卸载失败",
        deleteFailed: "删除失败",
        confirmDeleteModel: "确定要删除模型吗？",
        resourceUsage: "资源占用",
        memory: "内存",
        cpuLabel: "CPU",
        cacheSizeLabel: "缓存大小",
        runningStatus: "运行中",
        loadingModel: "加载中...",
        loadModel: "加载",
        unloadingModel: "卸载中...",
        unloadModel: "卸载",
        deleteModel: "删除",
        fileStatusLabel: "文件状态",
        recommended: "推荐",
        supportsEnZh: "支持中英",
        downloadModel: "下载",
        downloadingModel: "下载中...",
        quickActions: "快速操作",
        clearTranslationCache: "清空翻译缓存",
        unloadCurrentModel: "卸载当前模型",
        localModels: "本地模型",
        noLocalModels: "暂无本地模型，请从下方列表下载",
        availableModels: "可用模型",
        loadingHint: "加载中...",
        loadingModelsFromHf: "正在从 HuggingFace 获取模型列表...",
        cannotFetchModels: "无法获取模型列表，请检查网络连接",
        downloadsCount: "下载",
        // CommandsGuidePage
        commandsGuideTitle: "Commands 使用指南",
        commandsGuideSubtitle: "cc-spec 提供标准化的 7 步工作流，帮助您高效管理 AI 辅助开发",
        back: "返回",
        workflowOverview: "工作流概览",
        usageExample: "使用示例",
        usageTips: "使用技巧",
        faq: "常见问题",
        faqHowToStart: "如何开始使用？",
        faqHowToStartAnswer: "首先确保已安装 Commands 到项目。在 Claude Code 中输入",
        faqHowToStartAnswer2: "开始描述需求，系统将引导您完成整个工作流。",
        faqCanSkipStages: "可以跳过某些阶段吗？",
        faqCanSkipStagesAnswer: "工作流设计为顺序执行，但对于简单任务，您可以使用",
        faqCanSkipStagesAnswer2: "快速记录小变更。",
        faqTaskFailed: "任务执行失败怎么办？",
        faqTaskFailedAnswer: "使用",
        faqTaskFailedAnswer2: "审查任务结果，可以标记返工项让系统重新执行。",
        faqViewHistory: "如何查看变更历史？",
        faqViewHistoryAnswer: "使用",
        faqViewHistoryAnswer2: "查看活跃变更和归档记录，支持按类型和状态筛选。",
        // Commands 描述
        cmdSpecifyDesc: "与用户确认需求，输出 proposal.md",
        cmdSpecifyTip1: "在开始新功能开发前使用",
        cmdSpecifyTip2: "会生成 proposal.md 作为需求文档",
        cmdSpecifyTip3: "建议先描述清楚功能目标和范围",
        cmdClarifyDesc: "CC↔CX 讨论或用户审查",
        cmdClarifyTip1: "用于审查任务执行结果",
        cmdClarifyTip2: "可以标记返工项",
        cmdClarifyTip3: "支持评分验收",
        cmdPlanDesc: "用户确认后生成 tasks.yaml",
        cmdPlanTip1: "根据 proposal.md 生成执行计划",
        cmdPlanTip2: "每个任务包含明确的验收标准",
        cmdPlanTip3: "支持 Wave 分组并行执行",
        cmdApplyDesc: "使用 SubAgent 执行任务",
        cmdApplyTip1: "可以指定具体任务 ID 执行",
        cmdApplyTip2: "支持批量执行整个 Wave",
        cmdApplyTip3: "执行结果会自动记录",
        cmdAcceptDesc: "端到端验收",
        cmdAcceptTip1: "验收所有任务完成情况",
        cmdAcceptTip2: "生成最终验收报告",
        cmdAcceptTip3: "通过后可以归档变更",
        cmdArchiveDesc: "归档已完成的变更",
        cmdArchiveTip1: "将变更移动到 archive 目录",
        cmdArchiveTip2: "保留完整的变更历史",
        cmdArchiveTip3: "支持后续回溯查询",
    },
    en: {
        title: "cc-spec tools",
        subtitle: "Project hub and execution monitor",
        clearRuns: "Clear",
        runs: "Runs",
        waitingEvents: "Waiting for Codex...",
        projects: "Projects",
        projectHint: "Import a local project to manage sessions, indexes, and skills.",
        currentProject: "Current Project",
        noProjectSelected: "No project selected",
        projectPathPlaceholder: "Enter project path (e.g. C:\\develop\\cc-spec)",
        projectPathRequired: "Please enter a project path",
        importProject: "Import Project",
        refresh: "Refresh",
        projectList: "Project List",
        setCurrent: "Set Current",
        removeProject: "Remove",
        noProjects: "No projects yet",
        openClaudeTerminal: "Open Claude Terminal",
        loading: "Loading",
        projectNotFound: "Project not found or removed",
        confirmRemoveProject: "Remove this project from the list?",
        cancel: "Cancel",
        removeProjectDialogTitle: "Remove project",
        removeProjectDialogSubtitle: "Optionally back up requirements; everything else will be cleaned",
        removeProjectDialogDesc: "Choosing “Uninstall & clean, then remove” deletes .cc-spec/, .cc-specignore, .claude/commands/cc-spec*, .claude/skills/cc-spec-standards, and clears local tool history and project state.",
        backupRequirementsLabel: "Back up requirements before deleting",
        backupRequirementsHint: "Exports proposal.md / detail.md / review.md / mini-proposal.md only",
        backupSaveDialogTitle: "Choose requirements backup location",
        backupPathInProjectError: "Backup file cannot be saved inside the project folder (cleanup will delete it). Choose another location.",
        removeProjectOnly: "Remove from list only",
        removeProjectCleanupAndRemove: "Uninstall & clean, then remove",
        removeProjectWorking: "Working...",
        selectProjectHint: "Import and select a project to view runs grouped by project.",
        projectEmpty: "No runs yet",
        projectEmptyHint: "There are no Codex runs for the current project.",
        navProjects: "Projects",
        navRuns: "Runs",
        navCommandsGuide: "Commands Guide",
        enterProject: "Enter",
        backToProjects: "Back to Projects",
        projectTabOverview: "Overview",
        projectTabSkills: "Skills",
        projectTabArtifacts: "Artifacts",
        projectTabRuns: "Runs",
        projectTabCodex: "Codex",
        yes: "Yes",
        no: "No",
        openInVSCode: "Open in VS Code",
        empty: "Empty",
        projectIndexTitle: "Index",
        projectIndexInitialized: "Initialized",
        projectIndexLevels: "Levels",
        projectIndexFiles: "Files",
        projectIndexUpdatedAt: "Updated",
        reinitIndex: "Re-initialize",
        projectChangesTitle: "Changes",
        projectChangesHint: "Reads status.yaml from .cc-spec/changes",
        projectChangesCount: "Count",
        projectChangesEmpty: "No changes yet",
        artifactsTitle: "cc-spec artifacts",
        artifactsHint: "Browse cc-spec outputs (edit in VS Code by default)",
        artifactsBrowser: "Browser",
        artifactFolder: "Folder",
        notGenerated: "Missing",
        notGeneratedHint: "This item is not generated or has been cleaned",
        up: "Up",
        emptyFolder: "Empty folder",
        preview: "Preview",
        reveal: "Reveal in file manager",
        copyPath: "Copy path",
        jumpToLine: "Jump to line",
        openAtLine: "Open at line",
        previewFromLine: "Preview from line",
        selectArtifactHint: "Select an artifact root/file",
        selectFileHint: "Select a file to preview (directories are for browsing)",
        lines: "Lines",
        truncated: "truncated",
        loadMore: "More",
        noPreview: "Nothing to preview",
        commandsTitle: "Commands Manager",
        commandsHint: "Install cc-spec commands into .claude/commands for this project.",
        commandsVersion: "Bundled Version",
        commandsUpdateNeeded: "Update Needed",
        commandsUpToDate: "Up to Date",
        commandsInstall: "Install/Update",
        commandsUninstall: "Uninstall",
        commandsRefresh: "Refresh",
        commandsNoProject: "Select a project to manage commands.",
        pause: "Pause",
        send: "Send",
        projectCodexHint: "Use Codex in a native terminal; the tool manages sessions, control and results.",
        projectCodexNewSession: "New session",
        projectCodexSessions: "Sessions",
        projectCodexSelected: "Selected session",
        projectCodexSend: "Send a prompt (inject into terminal)",
        projectCodexPromptPlaceholder: "e.g. Summarize this project structure...",
        projectCodexSendHint: "Claude Code can subscribe to codex.managed.turn_complete for final results",
        projectCodexLastResult: "Last result",
        commandsEmpty: "No commands status yet. Refresh or install.",
        commandsInstalled: "Installed",
        commandsMissing: "Missing",
        active: "Active",
        completed: "Done",
        statusLive: "Running",
        statusDone: "Done",
        statusFailed: "Failed",
        statusIdle: "Idle",
        started: "Started",
        finished: "Finished",
        duration: "Duration",
        exitCode: "Exit",
        errorType: "Error",
        noOutput: "No output",
        connecting: "Connecting...",
        connected: "Connected",
        connectionError: "Reconnecting...",
        port: "Port",
        langMode: "中文",
        copy: "Copy",
        copied: "Copied",
        darkMode: "Dark",
        lightMode: "Light",
        stop: "Stop",
        stopping: "Stopping...",
        // IndexPrompt
        indexPromptTitle: "Project Initialization (Required)",
        indexPromptSubtitle: "Generate Commands/Standards and initialize index",
        indexPromptDesc: "This will run: (1) Bootstrap (generate .claude/commands and standards); (2) Index (generate PROJECT_INDEX/FOLDER_INDEX). Select index levels (recommended: L1 + L2):",
        indexL1Name: "L1 - Summary",
        indexL1Desc: "Project structure overview",
        indexL2Name: "L2 - Symbols",
        indexL2Desc: "Functions, classes, exports",
        indexL3Name: "L3 - Details",
        indexL3Desc: "Full code analysis (slower)",
        indexDontAskAgain: "Don't ask again",
        indexSkip: "Skip",
        indexInitialize: "Initialize",
        indexInitializing: "Initializing...",
        // TriggerEditor
        keywordExists: "Keyword already exists",
        invalidRegex: "Invalid regular expression",
        patternExists: "Pattern already exists",
        enterKeyword: "Enter keyword, press Enter to add",
        enterRegex: "Enter regex pattern, press Enter to add",
        testText: "Enter test text to see real-time matching results...",
        matchTest: "Testing...",
        // BodyEditor
        edit: "Edit",
        saving: "Saving...",
        save: "Save",
        enterMarkdown: "Write Markdown content here...",
        // SkillsPage
        workflow: "Workflow",
        domain: "Domain",
        execution: "Execution",
        enabled: "Enabled",
        disabled: "Disabled",
        details: "Details",
        collapse: "Collapse",
        scanDirectory: "Scan Directory",
        // ProjectSkillsPanel
        skillsUpdated: "Project Skills status updated",
        scanning: "Scanning...",
        scanProjectDir: "Scan Project Directory",
        removeFromProject: "Remove from project",
        selectProjectFirst: "Please select a project first",
        clickToScan: "Click 'Scan Project Directory' to detect project skills",
        // ProjectCodexPanel
        confirmStopAndDelete: "Confirm: Session is still running. Stop and delete?",
        confirmDeleteSession: "Confirm: Delete this session?",
        deleteSession: "Delete session (stop if running)",
        sessionStatus: "Session status",
        // TitleBar
        minimize: "Minimize",
        maximizeRestore: "Maximize/Restore",
        close: "Close",
        // Settings 页面
        settingsTitle: "Settings",
        settingsDesc: "Configure app parameters, concurrency limits, and model options",
        goBack: "Back",
        savingSettings: "Saving...",
        saveSettings: "Save Settings",
        settingsSaved: "Settings saved!",
        concurrencyStatus: "Concurrency Status",
        queued: "queued",
        total: "Total",
        concurrencyLimitReached: "Concurrency limit reached, new tasks will be queued",
        claudeConfig: "Claude Config",
        execPath: "Execution Path",
        autoDetect: "Auto Detect",
        customPath: "Custom Path",
        enterClaudePath: "Enter claude executable path",
        maxConcurrent: "Max Concurrent",
        suggestedValue: "Suggested: 1-2",
        uiDisplay: "UI Display",
        theme: "Theme",
        followSystem: "Follow System",
        darkTheme: "Dark Mode",
        lightTheme: "Light Mode",
        languageLabel: "Language",
        chineseSimplified: "简体中文",
        englishLang: "English",
        codexConfig: "Codex Config",
        indexSettings: "Index Settings",
        enableMultiLevelIndex: "Enable Multi-level Index",
        autoUpdateIndex: "Auto Update Index",
        translationModel: "Translation Model",
        loaded: "Loaded",
        downloaded: "Downloaded",
        notDownloaded: "Not Downloaded",
        currentModelLabel: "Current Model",
        noneModel: "None",
        fileSize: "File Size",
        cacheEntriesLabel: "Cache Entries",
        translationModelDesc: "Download various translation models from HuggingFace, including T5, Opus MT, etc.",
        openModelManager: "Open Model Manager",
        refreshStatus: "Refresh Status",
        clearCache: "Clear Cache",
        // ModelManager 页面
        modelManager: "Model Manager",
        modelManagerDesc: "Download, load, and manage translation models. Monitor resource usage.",
        refreshing: "Refreshing...",
        backToSettings: "Back to Settings",
        loadFailed: "Load Failed",
        downloadFailed: "Download Failed",
        unloadFailed: "Unload Failed",
        deleteFailed: "Delete Failed",
        confirmDeleteModel: "Are you sure you want to delete this model?",
        resourceUsage: "Resource Usage",
        memory: "Memory",
        cpuLabel: "CPU",
        cacheSizeLabel: "Cache Size",
        runningStatus: "Running",
        loadingModel: "Loading...",
        loadModel: "Load",
        unloadingModel: "Unloading...",
        unloadModel: "Unload",
        deleteModel: "Delete",
        fileStatusLabel: "File Status",
        recommended: "Recommended",
        supportsEnZh: "EN-ZH",
        downloadModel: "Download",
        downloadingModel: "Downloading...",
        quickActions: "Quick Actions",
        clearTranslationCache: "Clear Translation Cache",
        unloadCurrentModel: "Unload Current Model",
        localModels: "Local Models",
        noLocalModels: "No local models. Download from the list below.",
        availableModels: "Available Models",
        loadingHint: "Loading...",
        loadingModelsFromHf: "Fetching model list from HuggingFace...",
        cannotFetchModels: "Cannot fetch model list. Check your network connection.",
        downloadsCount: "downloads",
        // CommandsGuidePage
        commandsGuideTitle: "Commands Guide",
        commandsGuideSubtitle: "cc-spec provides a standardized 7-step workflow to help you manage AI-assisted development efficiently",
        back: "Back",
        workflowOverview: "Workflow Overview",
        usageExample: "Usage Example",
        usageTips: "Usage Tips",
        faq: "FAQ",
        faqHowToStart: "How to get started?",
        faqHowToStartAnswer: "First, ensure Commands are installed in the project. In Claude Code, enter",
        faqHowToStartAnswer2: "to start describing requirements. The system will guide you through the workflow.",
        faqCanSkipStages: "Can I skip certain stages?",
        faqCanSkipStagesAnswer: "The workflow is designed to be sequential, but for simple tasks, you can use",
        faqCanSkipStagesAnswer2: "to quickly record small changes.",
        faqTaskFailed: "What if a task fails?",
        faqTaskFailedAnswer: "Use",
        faqTaskFailedAnswer2: "to review task results and mark items for rework.",
        faqViewHistory: "How to view change history?",
        faqViewHistoryAnswer: "Use",
        faqViewHistoryAnswer2: "to view active changes and archived records, with filtering by type and status.",
        // Commands 描述
        cmdSpecifyDesc: "Confirm requirements with user, output proposal.md",
        cmdSpecifyTip1: "Use before starting new feature development",
        cmdSpecifyTip2: "Generates proposal.md as requirement document",
        cmdSpecifyTip3: "Recommended to describe feature goals and scope clearly",
        cmdClarifyDesc: "CC↔CX discussion or user review",
        cmdClarifyTip1: "Used for reviewing task execution results",
        cmdClarifyTip2: "Can mark items for rework",
        cmdClarifyTip3: "Supports scoring acceptance",
        cmdPlanDesc: "Generate tasks.yaml after user confirmation",
        cmdPlanTip1: "Generate execution plan based on proposal.md",
        cmdPlanTip2: "Each task includes clear acceptance criteria",
        cmdPlanTip3: "Supports Wave grouping for parallel execution",
        cmdApplyDesc: "Execute tasks using SubAgent",
        cmdApplyTip1: "Can specify specific task ID to execute",
        cmdApplyTip2: "Supports batch execution of entire Wave",
        cmdApplyTip3: "Execution results are automatically recorded",
        cmdAcceptDesc: "End-to-end acceptance",
        cmdAcceptTip1: "Accept completion status of all tasks",
        cmdAcceptTip2: "Generate final acceptance report",
        cmdAcceptTip3: "Can archive changes after passing",
        cmdArchiveDesc: "Archive completed changes",
        cmdArchiveTip1: "Move changes to archive directory",
        cmdArchiveTip2: "Preserve complete change history",
        cmdArchiveTip3: "Support retrospective queries",
    },
};

export const BG_IMAGES = [
    '122.png',
    '6fc129ee-5c9e-4f10-804b-0f73f198347b.png',
    'A8430D51D6F00D3A6CE72F04DC47C8FE.gif',
    'miao.gif',
    'ScreenShot_2025-12-17_175919_945.png',
    'wu.jpg'
];
